### PR TITLE
Fix/email popup mode redirection

### PR DESCRIPTION
**Pull request by Keddib**
On email popup flow, the redirection is still happening on the parent window

https://github.com/didit-protocol/didit-sdk/assets/52551794/bbb2b660-4d59-45e2-bfde-09beb58e5fde

I think in the popup mode, the redirection should happen on the popup only, and we get the code from the parent window and preserve the application state

### CODE REVIEW

**Comment by pablogamium** [comment]
> On email popup flow, the redirection is still happening on the parent window
> 
>  Screen.Recording.2023-11-05.at.13.16.37.mov 
> I think in the popup mode, the redirection should happen on the popup only, and we get the code from the parent window and preserve the application state

The oauth flow provides a configurable callback or redirect URI param so you can retrieve the token in your client application. Retrieving it in thee popup and send it back to client application is less secture

**Comment by Keddib** [comment]
> sect¡ure.

The problem is why we redirect in both the popup and the parent window ?

**Comment by pablogamium** [comment]
> > sect¡ure.
> 
> The problem is why we redirect in both the popup and the parent window ?

The popup is redirected by the auth system. Then the popup propagates to parent one, client, which is the one should retrieve the token (does the request to /token)

**Comment by Keddib** [comment]
> > On email popup flow, the redirection is still happening on the parent window
> > Screen.Recording.2023-11-05.at.13.16.37.mov
> > I think in the popup mode, the redirection should happen on the popup only, and we get the code from the parent window and preserve the application state
> 
> The oauth flow provides a configurable callback or redirect URI param so you can retrieve the token in your client application. Retrieving it in thee popup and send it back to client application is less sect¡ure. Alejandro wants it like that

I don't understand, but the popup is used to authenticate without losing the the application state in single page application. but if we Are going to redirect on the parent window. we can do 

> > > sect¡ure.
> > 
> > 
> > The problem is why we redirect in both the popup and the parent window ?
> 
> The popup is redirected by the auth system. Then the popup propagates to parent one, client, which is the one should retrieve the token (does the request to /token)

**Pull request closed without merging**
